//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb.ProxyHuesped {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HuespedReporteBE", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class HuespedReporteBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HuespedBE", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class HuespedBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTipoDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPaisField, value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTipoDoc {
            get {
                return this.IdTipoDocField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTipoDocField, value) != true)) {
                    this.IdTipoDocField = value;
                    this.RaisePropertyChanged("IdTipoDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDoc {
            get {
                return this.NumDocField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocField, value) != true)) {
                    this.NumDocField = value;
                    this.RaisePropertyChanged("NumDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDoc {
            get {
                return this.TipoDocField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocField, value) != true)) {
                    this.TipoDocField = value;
                    this.RaisePropertyChanged("TipoDoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyHuesped.IServiceHuesped")]
    public interface IServiceHuesped {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHuesped/contarHuespedesPorPais", ReplyAction="http://tempuri.org/IServiceHuesped/contarHuespedesPorPaisResponse")]
        AplicacionWeb.ProxyHuesped.HuespedReporteBE[] contarHuespedesPorPais(System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHuesped/contarHuespedesPorPais", ReplyAction="http://tempuri.org/IServiceHuesped/contarHuespedesPorPaisResponse")]
        System.Threading.Tasks.Task<AplicacionWeb.ProxyHuesped.HuespedReporteBE[]> contarHuespedesPorPaisAsync(System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHuesped/obtenerHuespedesPorPais", ReplyAction="http://tempuri.org/IServiceHuesped/obtenerHuespedesPorPaisResponse")]
        AplicacionWeb.ProxyHuesped.HuespedBE[] obtenerHuespedesPorPais(System.DateTime fechaInicio, System.DateTime fechaFinal, string idPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHuesped/obtenerHuespedesPorPais", ReplyAction="http://tempuri.org/IServiceHuesped/obtenerHuespedesPorPaisResponse")]
        System.Threading.Tasks.Task<AplicacionWeb.ProxyHuesped.HuespedBE[]> obtenerHuespedesPorPaisAsync(System.DateTime fechaInicio, System.DateTime fechaFinal, string idPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHuesped/obtenerDineroGastadoPorHuesped", ReplyAction="http://tempuri.org/IServiceHuesped/obtenerDineroGastadoPorHuespedResponse")]
        decimal obtenerDineroGastadoPorHuesped(System.DateTime fechaInicio, System.DateTime fechaFinal, string idTipoDoc, string numDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHuesped/obtenerDineroGastadoPorHuesped", ReplyAction="http://tempuri.org/IServiceHuesped/obtenerDineroGastadoPorHuespedResponse")]
        System.Threading.Tasks.Task<decimal> obtenerDineroGastadoPorHuespedAsync(System.DateTime fechaInicio, System.DateTime fechaFinal, string idTipoDoc, string numDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHuesped/registrarHuesped", ReplyAction="http://tempuri.org/IServiceHuesped/registrarHuespedResponse")]
        bool registrarHuesped(AplicacionWeb.ProxyHuesped.HuespedBE objHuespedBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHuesped/registrarHuesped", ReplyAction="http://tempuri.org/IServiceHuesped/registrarHuespedResponse")]
        System.Threading.Tasks.Task<bool> registrarHuespedAsync(AplicacionWeb.ProxyHuesped.HuespedBE objHuespedBE);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHuespedChannel : AplicacionWeb.ProxyHuesped.IServiceHuesped, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHuespedClient : System.ServiceModel.ClientBase<AplicacionWeb.ProxyHuesped.IServiceHuesped>, AplicacionWeb.ProxyHuesped.IServiceHuesped {
        
        public ServiceHuespedClient() {
        }
        
        public ServiceHuespedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHuespedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHuespedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHuespedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplicacionWeb.ProxyHuesped.HuespedReporteBE[] contarHuespedesPorPais(System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.contarHuespedesPorPais(fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<AplicacionWeb.ProxyHuesped.HuespedReporteBE[]> contarHuespedesPorPaisAsync(System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.contarHuespedesPorPaisAsync(fechaInicio, fechaFinal);
        }
        
        public AplicacionWeb.ProxyHuesped.HuespedBE[] obtenerHuespedesPorPais(System.DateTime fechaInicio, System.DateTime fechaFinal, string idPais) {
            return base.Channel.obtenerHuespedesPorPais(fechaInicio, fechaFinal, idPais);
        }
        
        public System.Threading.Tasks.Task<AplicacionWeb.ProxyHuesped.HuespedBE[]> obtenerHuespedesPorPaisAsync(System.DateTime fechaInicio, System.DateTime fechaFinal, string idPais) {
            return base.Channel.obtenerHuespedesPorPaisAsync(fechaInicio, fechaFinal, idPais);
        }
        
        public decimal obtenerDineroGastadoPorHuesped(System.DateTime fechaInicio, System.DateTime fechaFinal, string idTipoDoc, string numDoc) {
            return base.Channel.obtenerDineroGastadoPorHuesped(fechaInicio, fechaFinal, idTipoDoc, numDoc);
        }
        
        public System.Threading.Tasks.Task<decimal> obtenerDineroGastadoPorHuespedAsync(System.DateTime fechaInicio, System.DateTime fechaFinal, string idTipoDoc, string numDoc) {
            return base.Channel.obtenerDineroGastadoPorHuespedAsync(fechaInicio, fechaFinal, idTipoDoc, numDoc);
        }
        
        public bool registrarHuesped(AplicacionWeb.ProxyHuesped.HuespedBE objHuespedBE) {
            return base.Channel.registrarHuesped(objHuespedBE);
        }
        
        public System.Threading.Tasks.Task<bool> registrarHuespedAsync(AplicacionWeb.ProxyHuesped.HuespedBE objHuespedBE) {
            return base.Channel.registrarHuespedAsync(objHuespedBE);
        }
    }
}
