//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb.ProxyUbigeo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaisBE", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PaisBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPaisField, value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartamentoBE", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class DepartamentoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDepartamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDepartamento {
            get {
                return this.IdDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDepartamentoField, value) != true)) {
                    this.IdDepartamentoField = value;
                    this.RaisePropertyChanged("IdDepartamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProvinciaBE", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ProvinciaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProvincia {
            get {
                return this.IdProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdProvinciaField, value) != true)) {
                    this.IdProvinciaField = value;
                    this.RaisePropertyChanged("IdProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistritoBE", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class DistritoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDistritoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDistrito {
            get {
                return this.IdDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDistritoField, value) != true)) {
                    this.IdDistritoField = value;
                    this.RaisePropertyChanged("IdDistrito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUbigeo.IServiceUbigeo")]
    public interface IServiceUbigeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUbigeo/obtenerPaises", ReplyAction="http://tempuri.org/IServiceUbigeo/obtenerPaisesResponse")]
        AplicacionWeb.ProxyUbigeo.PaisBE[] obtenerPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUbigeo/obtenerPaises", ReplyAction="http://tempuri.org/IServiceUbigeo/obtenerPaisesResponse")]
        System.Threading.Tasks.Task<AplicacionWeb.ProxyUbigeo.PaisBE[]> obtenerPaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUbigeo/obtenerDepartamentos", ReplyAction="http://tempuri.org/IServiceUbigeo/obtenerDepartamentosResponse")]
        AplicacionWeb.ProxyUbigeo.DepartamentoBE[] obtenerDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUbigeo/obtenerDepartamentos", ReplyAction="http://tempuri.org/IServiceUbigeo/obtenerDepartamentosResponse")]
        System.Threading.Tasks.Task<AplicacionWeb.ProxyUbigeo.DepartamentoBE[]> obtenerDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUbigeo/obtenerProvincias", ReplyAction="http://tempuri.org/IServiceUbigeo/obtenerProvinciasResponse")]
        AplicacionWeb.ProxyUbigeo.ProvinciaBE[] obtenerProvincias(string idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUbigeo/obtenerProvincias", ReplyAction="http://tempuri.org/IServiceUbigeo/obtenerProvinciasResponse")]
        System.Threading.Tasks.Task<AplicacionWeb.ProxyUbigeo.ProvinciaBE[]> obtenerProvinciasAsync(string idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUbigeo/obtenerDistritos", ReplyAction="http://tempuri.org/IServiceUbigeo/obtenerDistritosResponse")]
        AplicacionWeb.ProxyUbigeo.DistritoBE[] obtenerDistritos(string idDepartamento, string idProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUbigeo/obtenerDistritos", ReplyAction="http://tempuri.org/IServiceUbigeo/obtenerDistritosResponse")]
        System.Threading.Tasks.Task<AplicacionWeb.ProxyUbigeo.DistritoBE[]> obtenerDistritosAsync(string idDepartamento, string idProvincia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUbigeoChannel : AplicacionWeb.ProxyUbigeo.IServiceUbigeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUbigeoClient : System.ServiceModel.ClientBase<AplicacionWeb.ProxyUbigeo.IServiceUbigeo>, AplicacionWeb.ProxyUbigeo.IServiceUbigeo {
        
        public ServiceUbigeoClient() {
        }
        
        public ServiceUbigeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUbigeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUbigeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplicacionWeb.ProxyUbigeo.PaisBE[] obtenerPaises() {
            return base.Channel.obtenerPaises();
        }
        
        public System.Threading.Tasks.Task<AplicacionWeb.ProxyUbigeo.PaisBE[]> obtenerPaisesAsync() {
            return base.Channel.obtenerPaisesAsync();
        }
        
        public AplicacionWeb.ProxyUbigeo.DepartamentoBE[] obtenerDepartamentos() {
            return base.Channel.obtenerDepartamentos();
        }
        
        public System.Threading.Tasks.Task<AplicacionWeb.ProxyUbigeo.DepartamentoBE[]> obtenerDepartamentosAsync() {
            return base.Channel.obtenerDepartamentosAsync();
        }
        
        public AplicacionWeb.ProxyUbigeo.ProvinciaBE[] obtenerProvincias(string idDepartamento) {
            return base.Channel.obtenerProvincias(idDepartamento);
        }
        
        public System.Threading.Tasks.Task<AplicacionWeb.ProxyUbigeo.ProvinciaBE[]> obtenerProvinciasAsync(string idDepartamento) {
            return base.Channel.obtenerProvinciasAsync(idDepartamento);
        }
        
        public AplicacionWeb.ProxyUbigeo.DistritoBE[] obtenerDistritos(string idDepartamento, string idProvincia) {
            return base.Channel.obtenerDistritos(idDepartamento, idProvincia);
        }
        
        public System.Threading.Tasks.Task<AplicacionWeb.ProxyUbigeo.DistritoBE[]> obtenerDistritosAsync(string idDepartamento, string idProvincia) {
            return base.Channel.obtenerDistritosAsync(idDepartamento, idProvincia);
        }
    }
}
