//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospedajeEntities : DbContext
    {
        public HospedajeEntities()
            : base("name=HospedajeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ambiente> Ambiente { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Huesped> Huesped { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<ReservaDetalle> ReservaDetalle { get; set; }
        public virtual DbSet<ReservaHuesped> ReservaHuesped { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoPago> TipoPago { get; set; }
        public virtual DbSet<Ubigeo> Ubigeo { get; set; }
    }
}
