//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int id { get; set; }
        public string idTipoDoc { get; set; }
        public string numDoc { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string domicilio { get; set; }
        public string idUbigeo { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public bool estado { get; set; }
    
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
